import random
#Projekt 2 - Zgadnij liczbę - Jakub Grzebielucha 59599
def zagadka():
    number_to_guess = random.randint(1, 100)
    attempts = 0
    print("Welcome to the game! You have to guess the number generated by the code in the least number of attempts. Good luck!!!")
    while True:
      try:
        user_input = input("Enter the number: ")
        guess = int(user_input)
        if guess > 100 or guess < 1:
            raise ValueError
        if guess < number_to_guess:
            print("The number you are looking for is bigger.")
            attempts += 1
        elif guess > number_to_guess:
            print("The number you are looking for is smaller.")
            attempts += 1
        elif guess == number_to_guess:
            attempts += 1
            print("Congrats!! You found hidden number!! This number was:",number_to_guess,"and you found it in", attempts, "attempt.")
            break
      except TypeError:
          attempts += 1
          print("Error: Please enter an integer between 1 and 100.")
      except ValueError:
          attempts += 1
          print("Error: Please enter an integer between 1 and 100.")

zagadka()